name: Execute a script
on: [push]
jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
    #   - name: Make the script files executable
    #     run: chmod +x hello-world.sh
      - name: Run the scripts
        run: bash ./hello-world.sh