name: Github Context
on: push

jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Ref
        run: echo ${{ github.ref }}
      - name: Event
        run: echo ${{ github.event.organization.id }}