name: Github Context
run-name: ${{ github.actor }} is gathering github context
on: 
  push:
    branches-ignore:
      - 'main'

jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Ref
        run: echo ${{ github.ref }}
      - name: Event
        run: echo ${{ github.event.organization.id }}