name: Github Context
run-name: ${{ github.actor }} is gathering github context
on:
  workflow_dispatch:

  push:
    branches-ignore:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '.github/**'

jobs:
  github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Ref
        run: echo ${{ github.ref }}
      - name: Event
        run: echo ${{ github.event.organization.id }}
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY